# Generated by Django 4.2.30 on 2026-06-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paystack_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
