# Generated by Django 4.2.30 on 2026-06-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='paystack_subaccount_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
